### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by rahulramaprasad7** [cu-ecen-5013/final-project-rahulramaprasad7#3]
1) Fetch magnetometer values from IMU sensor and pipe the stream of sensor values into the sensor fusion algorithm and output the quaternion set for every time the sensor values are read.
2) Look into the algorithm and multi thread some of the blocks of the algorithm such as initialisation and calculation rate of change of gyroscope and normalisation.
DoD : Provide a continuous estimation of the orientation of the sensor using Euler angles (Roll, pitch and Yaw) by fusing the stream of incoming 9-axis  values from the IMU sensor .
Monitor the thread count of the process using the command "watch ps -o thcount <pid>"

**Comment by steveantony5** [comment]
@rahulramaprasad7  Please update the Dod in an understandable way. How do I verify that your sensor fusion algorithm works?

Also I don't understand the work of sensor fusion algorithm as your project overview page doesn't describe about it?

Please answer these questions in your project overview page.
What is the need of sensor fusion algorithm? What does it do?
I understand that you get raw value of data from your IMU sensor and you give those raw data to the sensor fusion algorithm.

**Comment by rahulramaprasad7** [comment]
Succesfully interfaced magnetometer to obtain 9-axis values from IMU sensor, fed it into the Madgwick sensor fusion algorithm to calculate the orientation in terms of Roll, pitch and Yaw.
Multithreaded the Madgwick fusion algorithm to create threads for gyroscope quaternion calculation and accelerometer-magnetometer calibration and verified the threads spawning by using debug print statements in the thread handlers and adding error handling in case of thread create or join failures. 
https://github.com/cu-ecen-5013/final-project-rahulramaprasad7/commit/5fe23dfb7745474e859eb6c6d6e7e4454774d770
